micronaut:
  application:
    name: kmd-booking
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/css/**"
        paths: "classpath:css"

booking:
  authenticationCode: ${BOOKING_AUTHENTICATION_CODE}
  url: https://booking-ltk.kmd.dk
  path: /kmd_webapi/api/Monitor/GetFilteredAccessControlRecords?dateTimeFrom={fromDate}&dateTimeTo={toDate}&facility=&facilityObject=&partObject=&authenticationCode={authenticationCode}&type=json
